attach(bank.full)
summary(bank.full)
str(bank.full)
bank.full$job=as.factor(bank.full$job)
bank.full$job=as.numeric(bank.full$job)
bank.full$marital=as.factor(bank.full$marital)
bank.full$marital=as.numeric(bank.full$marital)
bank.full$education=as.factor(bank.full$education)
bank.full$education=as.numeric(bank.full$education)
bank.full$default=as.factor(bank.full$default)
bank.full$default=as.numeric(bank.full$default)
bank.full$pdays=as.numeric(bank.full$pdays)
bank.full$campaign=as.numeric(bank.full$campaign)
bank.full$housing=as.factor(bank.full$housing)
bank.full$housing=as.numeric(bank.full$housing)
bank.full$loan=as.factor(bank.full$loan)
bank.full$loan=as.numeric(bank.full$loan)
bank.full$contact=as.factor(bank.full$contact)
bank.full$contact=as.numeric(bank.full$contact)
bank.full$month=as.factor(bank.full$month)
bank.full$month=as.numeric(bank.full$month)
bank.full$poutcome=as.factor(bank.full$poutcome)
bank.full$poutcome=as.numeric(bank.full$poutcome)
bank.full$y=as.factor(bank.full$y)
summary(bank.full)
str(bank.full)
logreg1=glm(y~.,data = bank.full,family = binomial)
summary(logreg1)
32631-24172
library(HH)
plot(logreg1)
logreg2=glm(bank.full$y~.,data = bank.full[,c(-2)],family = binomial)
summary(logreg2)
32631-24175
pred=predict(logreg2,type = "response",bank.full)
pred
cf=table(pred>0.5,bank.full$y)
cf
accuracy=sum(diag(cf))/sum(cf)
accuracy
#89.08
library(pROC)
roc(bank.full$y,logreg2$fitted.values,plot = TRUE)
#AUC=0.8716
roc(bank.full$y,logreg2$fitted.values,plot = TRUE,legacy.axes=TRUE)
