MLR_toyota=read.csv(file.choose())
View(MLR_toyota)
summary(MLR_toyota)
library(Boruta)
Data=MLR_toyota[,-1]
attach(Data)
library(caret)
library(mlbench)
var_sel=Boruta(Price~ .,data = Data)
print(var_sel)
#It tells that 3 attributes are unimpotant which are airbag_1, Cylinders, Power_Steering;
#3 tentative attributes left: Met_Color, Radio, Radio_cassette;
plot(var_sel,las=2,cex.axis=0.7)
Tentative_fix=TentativeRoughFix(var_sel)
print(Tentative_fix)
#30 attributes confirmed important: ABS, Age_08_04, Airbag_2, Airco, Automatic and 25 more;
#6 attributes confirmed unimportant: Airbag_1, Cylinders, Met_Color, Power_Steering, Radio and Radio_cassette
attStats(var_sel)
ncol(Data)
#Removing the unimprotant variables 
New_data=Data[,c(-9,-14,-22,-30,-31,-36)]
summary(New_data)
str(New_data)
New_data$Mfg_Month=as.numeric(New_data$Mfg_Month)
New_data$Fuel_Type=as.factor(New_data$Fuel_Type)
New_data$Fuel_Type=as.numeric(New_data$Fuel_Type)
New_data$Color=as.factor(New_data$Color)
New_data$Color=as.numeric(New_data$Color)
New_data$Color=as.numeric(New_data$HP)
New_data$Automatic=as.numeric(New_data$Automatic)
New_data$Mfr_Guarantee=as.numeric(New_data$Mfr_Guarantee)
New_data$BOVAG_Guarantee=as.numeric(New_data$BOVAG_Guarantee)
New_data$Airbag_2=as.numeric(New_data$Airbag_2)
New_data$Airco=as.numeric(New_data$Airco)
New_data$Automatic_airco=as.numeric(New_data$Automatic_airco)
New_data$Boardcomputer=as.numeric(New_data$Boardcomputer)
New_data$CD_Player=as.numeric(New_data$CD_Player)
New_data$Central_Lock=as.numeric(New_data$Central_Lock)
New_data$Powered_Windows=as.numeric(New_data$Powered_Windows)
New_data$Mistlamps=as.numeric(New_data$Mistlamps)
New_data$Sport_Model=as.numeric(New_data$Sport_Model)
New_data$Backseat_Divider=as.numeric(New_data$Backseat_Divider)
New_data$Metallic_Rim=as.numeric(New_data$Metallic_Rim)
New_data$Tow_Bar=as.numeric(New_data$Tow_Bar)
str(New_data)
hist(New_data$Price)
library(moments)
attach(New_data)
skewness(New_data$Price)
kurtosis(New_data$Price)
var(New_data$Price)
sd(New_data$Price)
names(New_data)
skewness(Age_08_04)
skewness(Color)
skewness(Fuel_Type)
skewness(Automatic)
skewness(Quarterly_Tax)
skewness(Mfr_Guarantee)
skewness(Boardcomputer)
skewness(Airbag_2)
skewness(Airco)
skewness(Automatic_airco)
skewness(Powered_Windows)
skewness(Mistlamps)
skewness(Sport_Model)
skewness(KM)
skewness(cc)
skewness(Gears)
skewness(HP)
skewness(Guarantee_Period)
skewness(Doors)
skewness(Weight)
skewness(Tow_Bar)
boxplot(Price)
boxplot(Age_08_04)
boxplot(KM)
boxplot(cc)
boxplot(Gears)
boxplot(HP)
boxplot(Guarantee_Period)
boxplot(Doors)
boxplot(Weight)
#Taking all inputs for the model except ABS and modelname
New_Data=New_data[,-c(1,19)]
str(New_Data)
cor(New_Data)
pairs(New_Data[,-c(3,6,8,9,15:30)])
cor(Age_08_04,KM)
#No corelinearity between input variables
attach(New_Data)
Model_1=lm(Price~.,data = New_Data)
summary(Model_1)
#Mfg_Year,Color,cc,doors,gears,Central_Lock,Mistlamps are insignificant.
library(HH)
vif(Model_1)
library(car)
avPlots(Model_1)
influenceIndexPlot(Model_1)
#81,110,222 are influencing datapoints
plot(Model_1)
#524,110,222,81 are outliers
#Model without influencing factors
model_2=lm(Price~.,data = New_Data[-c(524,81,110,222),])
summary(model_2)
#Mfg_Year,Color,cc,doors,gears,Central_Lock,Mistlamps are insignificant.
vif(model_2)
avPlots(model_2)
#taking log(cc) makes it significant
New_Data$cc=log(New_Data$cc)
model_3=lm(Price~.,data = New_Data[-c(524,81,110,222),-c(4,8,11,12,23,25)]  )
summary(model_3)
#now only automatic is insignificant
model_4=lm(Price~.,data = New_Data[-c(524,81,110,222),-c(4,8,9,11,12,23,25)])
summary(model_4)
vif(model_4)
avPlots(model_4)
#From added variable plot we can intrepret that Backseat_Divider,Metallic_Rim,Tow_Bar,
#Sport_Model,CD_Player,Powered_Windows,Airco,Boardcomputer,Airbag_2,Mfr_Guarantee have to be rejected.
plot(model_4)
model_5=lm(Price~Age_08_04+Mfg_Month+KM+Fuel_Type+HP+cc+Quarterly_Tax+Weight+BOVAG_Guarantee+Guarantee_Period+Automatic_airco,data=New_Data[-c(524,81,110,222),]) 
summary(model_5)
vif(model_5)
avPlots(model_5)
influenceIndexPlot(model_5)
plot(model_5)
#final model(Removing outliers 1059,961,602)
final_model=lm(Price~Age_08_04+Mfg_Month+KM+Fuel_Type+HP+cc+Quarterly_Tax+Weight+BOVAG_Guarantee+Guarantee_Period+Automatic_airco,data=New_Data[-c(524,81,110,222,1059,961,602),])
summary(final_model)
#R squared value=91.41%
#Adjusted r suare=91.35%
vif(final_model)
avPlots(final_model)
plot(final_model)
#Predicting values
confint(final_model,level = 0.95)
pred_val=as.data.frame(predict(final_model,interval = "predict"))
error=mean(pred_val$fit-New_Data$Price[-c(524,81,110,222,1059,961,602)])
sqrt(error)
cor(pred_val$fit,New_Data$Price[-c(524,81,110,222,1059,961,602)])#Accuracy=95.60%
